In [1]:
import torch


In [3]:
x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

tensor([-0.3119])
-0.3119075894355774
torch.float32


In [6]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)
y = torch.ones_like(x, device=device)
print(y)
x = x.to(device)
print(x)
z = x + y
print(z)
print(z.to('cpu', torch.double))

cpu
tensor([1.])
tensor([-0.3119])
tensor([0.6881])
tensor([0.6881], dtype=torch.float64)


다차원 텐서 표현

In [8]:
#1D
t1 =  torch.tensor([1,2,3])
print(t1.ndim)
print(t1.shape)
print(t1)

1
torch.Size([3])
tensor([1, 2, 3])


In [ ]:
#1D
t1 =  torch.tensor([1,2,3])
print(t1.ndim)
print(t1.shape)
print(t1)

In [10]:
#2D
t2 =  torch.tensor([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print(t2.ndim)
print(t2.shape)
print(t2)

2
torch.Size([3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [11]:
#3D
t3=  torch.tensor([[[1,2,3],
                   [4,5,6],
                   [7,8,9]],
                  [[1,2,3],
                   [4,5,6],
                   [7,8,9]],
                  [[1,2,3],
                   [4,5,6],
                   [7,8,9]]])
print(t3.ndim)
print(t3.shape)
print(t3)

3
torch.Size([3, 3, 3])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
