In [1]:
import torch
import math

In [3]:
a = torch.rand(1, 2) * 2 - 1
print(a)
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5))

tensor([[-0.7612,  0.3120]])
tensor([[0.7612, 0.3120]])
tensor([[-0., 1.]])
tensor([[-1.,  0.]])
tensor([[-0.5000,  0.3120]])


In [4]:
print(a)
print(torch.min(a))
print(torch.max(a))
print(torch.mean(a))
print(torch.std(a))
print(torch.prod(a))
print(torch.unique(torch.tensor([1,2,3,1,2,3])))

tensor([[-0.7612,  0.3120]])
tensor(-0.7612)
tensor(0.3120)
tensor(-0.2246)
tensor(0.7589)
tensor(-0.2375)
tensor([1, 2, 3])


In [8]:
# argmax : 최대값을 가진 인덱스
# argmin : 최소값을 가진 인덱스

x = torch.rand(2,2)
print(x)
print(x.max(dim=0))
print(x.max(dim=1))
print(x.min(dim=0))
print(x.min(dim=1))



tensor([[0.5057, 0.5229],
        [0.2530, 0.9198]])
torch.return_types.max(
values=tensor([0.5057, 0.9198]),
indices=tensor([0, 1]))
torch.return_types.max(
values=tensor([0.5229, 0.9198]),
indices=tensor([1, 1]))
torch.return_types.min(
values=tensor([0.2530, 0.5229]),
indices=tensor([1, 0]))
torch.return_types.min(
values=tensor([0.5057, 0.2530]),
indices=tensor([0, 0]))


In [9]:
x = torch.rand(2, 2)
print(x)
y = torch.rand(2, 2)
print(y)

tensor([[0.7198, 0.5949],
        [0.6429, 0.9088]])
tensor([[0.5913, 0.9025],
        [0.5399, 0.1689]])


In [15]:
print(x + y)
print(x - y)
print(torch.add(x, y))
print(torch.sub(x, y))

tensor([[1.3112, 1.4974],
        [1.1828, 1.0777]])
tensor([[ 0.1285, -0.3076],
        [ 0.1030,  0.7399]])
tensor([[1.3112, 1.4974],
        [1.1828, 1.0777]])
tensor([[ 0.1285, -0.3076],
        [ 0.1030,  0.7399]])


In [11]:
result = torch.empty(2,4)
torch.add(x,y, out=result)
print(result)

tensor([[1.3112, 1.4974],
        [1.1828, 1.0777]])


C:\Users\emily\AppData\Local\Temp\ipykernel_20132\2982148854.py:2: UserWarning: An output with one or more elements was resized since it had shape [2, 4], which does not match the required output shape [2, 2]. This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\Resize.cpp:35.)
  torch.add(x,y, out=result)


in-place 방식
- 텐서의 값을 변경하는 연산뒤에는 _"가 붙음
- x.copy_(y), x_t_()

In [13]:
print(x)
print(y)
y.add_(x)
print(y)

tensor([[0.7198, 0.5949],
        [0.6429, 0.9088]])
tensor([[0.5913, 0.9025],
        [0.5399, 0.1689]])
tensor([[1.3112, 1.4974],
        [1.1828, 1.0777]])


In [14]:
print(x)
print(y)
y.sub_(x)
print(y)

tensor([[0.7198, 0.5949],
        [0.6429, 0.9088]])
tensor([[1.3112, 1.4974],
        [1.1828, 1.0777]])
tensor([[0.5913, 0.9025],
        [0.5399, 0.1689]])


In [16]:
print(x * y)
print(torch.mul(x, y))
print(x.mul(y))

print(x / y)
print(torch.div(x, y))
print(x.div(y))

tensor([[0.4257, 0.5369],
        [0.3471, 0.1535]])
tensor([[0.4257, 0.5369],
        [0.3471, 0.1535]])
tensor([[0.4257, 0.5369],
        [0.3471, 0.1535]])
tensor([[1.2173, 0.6591],
        [1.1907, 5.3811]])
tensor([[1.2173, 0.6591],
        [1.1907, 5.3811]])
tensor([[1.2173, 0.6591],
        [1.1907, 5.3811]])


torch.mm : 내적 dot roduct

In [18]:
print(x)
print(y)
print(torch.matmul(x, y))
z = torch.mm(x, y)
print(z)
#분해
print(torch.svd(z))

tensor([[0.7198, 0.5949],
        [0.6429, 0.9088]])
tensor([[0.5913, 0.9025],
        [0.5399, 0.1689]])
tensor([[0.7468, 0.7501],
        [0.8708, 0.7337]])
tensor([[0.7468, 0.7501],
        [0.8708, 0.7337]])
torch.return_types.svd(
U=tensor([[-0.6808, -0.7325],
        [-0.7325,  0.6808]]),
S=tensor([1.5532, 0.0678]),
V=tensor([[-0.7380,  0.6748],
        [-0.6748, -0.7380]]))
