In [4]:
import torch
torch.__version__

'2.1.0+cu118'

In [5]:
X = torch.empty(4, 2)
print(X)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


무작위로 초기화된 텐서

In [6]:
X = torch.rand(4, 2)
print(X)

tensor([[0.2979, 0.0886],
        [0.0395, 0.2081],
        [0.4184, 0.5174],
        [0.1073, 0.2934]])


데이터 타입 long, 0으로 채워진 텐서

In [10]:
X = torch.zeros(4, 2, dtype=torch.long)
print(X)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])


사용자가 입력한 값으로 텐서 초기화

In [9]:
X = torch.tensor([3, 2.3])
print(X)

tensor([3.0000, 2.3000])


X와 같은 크기, float타입, 무작위로 채워진 텐서

In [11]:
X = torch.randn_like(X, dtype=torch.float)
print(X)

tensor([[ 0.4064,  0.8278],
        [ 1.3477,  0.0500],
        [ 0.8969,  2.1451],
        [-1.7005,  2.0102]])


텐서의 크기 계산

In [12]:
print(X.size())

torch.Size([4, 2])


데이터 타입 바꾸기

In [13]:
ft = torch.FloatTensor([1,2,3])
print(ft)
print(ft.dtype)

tensor([1., 2., 3.])
torch.float32


In [14]:
print(ft.short())
print(ft.int())
print(ft.long())

tensor([1, 2, 3], dtype=torch.int16)
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3])
